- name: Include vars
  include_vars: '{{ENV}}.yml'

- name: Clone Repo
  git:
    repo: '{{ repository }}'
    dest: '/home/{{ ansible_user }}/{{ app }}'
    version: '{{ branch }}'
    force: yes
    accept_hostkey: yes
    key_file: '/home/{{ ansible_user }}/.ssh/cgus-bot-key'
  tags:
    - setup
    - update
  register: result_git_clone

- name: Build the image
  become: yes
  community.general.docker_image:
    timeout: 600 # Build can take a long time as it pre-creates all pages
    source: build
    build:
      network: host
      pull: yes
      args:
        ENV_FILE: '{{ env_file }}'
      path: '/home/{{ ansible_user }}/{{ app }}'
    name: '{{ app }}:{{ result_git_clone.before[:8] }}'
    force_source: yes

- name: Start the container
  become: yes
  community.general.docker_container:
    name: '{{ app }}'
    image: '{{ app }}:{{ result_git_clone.before[:8] }}'
    restart: yes
    state: started
    restart_policy: unless-stopped
    etc_hosts:
      'mongo1': '172.17.0.1'
      'mongo2': '172.17.0.1'
      'mongo3': '172.17.0.1'
    env:
      AUTH_CREDENTIALS: "{{ nextauth_basic_auth if nextauth_basic_auth is defined else '' }}"
      AUTH_JWT_SECRET: "{{ nextauth_secret if nextauth_secret is defined else '' }}"
      PROCESSOR_API_URL: "{{ api_url if api_url is defined else '' }}"
      VERSION: '{{ result_git_clone.before[:8] }}'
    ports:
      - '{{ app_port }}:3000'

- name: Prune containers and images
  become: yes
  community.docker.docker_prune:
    containers: yes
    images: yes
    networks: false
    volumes: false
    builder_cache: false
