- name: Clone Repo
  git:
    repo: '{{ repository }}'
    dest: '/home/{{ ansible_user }}/{{ app }}'
    version: '{{branch}}'
    force: yes
    accept_hostkey: yes
    key_file: '/home/{{ ansible_user }}/.ssh/cgus-bot-key'
  tags:
    - setup
    - update

- debug:
    msg: 'Env file - {{ env_file }}'

- name: Build the image
  become: yes
  community.general.docker_image:
    source: build
    build:
      args:
        ENV_FILE: '{{ env_file }}'
      path: '/home/{{ ansible_user }}/{{ app }}'
    name: '{{ app }}'
    force_source: yes

- debug:
    msg: 'This is the env -{{ENV}}- and the base path --{{ base_path }}-- the app {{ app }} and the user {{ ansible_user }}'

- name: Start the container
  become: yes
  community.general.docker_container:
    name: '{{ app }}'
    image: '{{ app }}'
    restart: yes
    env:
      NODE_ENV: 'production'
      NEXT_PUBLIC_BASE_PATH: '{{ base_path }}'
    ports:
      - '{{ app_port }}:3000'
