- name: Clone Repo
  git:
    repo: "{{ repository }}"
    dest: "/home/{{ ansible_user }}/{{ app }}"
    version: "{{branch}}"
    force: yes
    accept_hostkey: yes
    key_file: "/home/{{ ansible_user }}/.ssh/cgus-bot-key"
  tags:
    - setup
    - update

- name: Build the image
  become: yes
  community.general.docker_image:
    source: build
    build:
      path: "/home/{{ ansible_user }}/{{ app }}"
    name: "{{ app }}"
    force_source: yes

- debug:
    msg: "This is the env -{{ENV}}- node env --{{ base_path }}-- {{ app }} {{ ansible_user }}"


- name: Start the container
  become: yes
  community.general.docker_container:
    name: "{{ app }}"
    image: "{{ app }}"
    restart: yes
    env:
      NODE_ENV: "production"
      BASE_PATH: "{{ base_path }}"
    ports:
      - "{{ app_port }}:3000"
