all:
  vars:
    ansible_user: debian
    repository: 'https://github.com/ambanum/information-manipulation-analyzer.git'
    nb_processors: '1'
    ansible_host: 51.89.231.68
    branch: 'main'
  children:
    preprod:
      hosts:
        preproduction:
          branch: 'develop'
          directory: 'ima-preproduction'
          port: '7821'
          env_directory: '.env.preproduction'
    prod:
      hosts:
        production:
          directory: 'ima-production'
          port: '7021'
          env_directory: '.env.production'
        tflmi-production:
          directory: 'ima-tflmi-production'
          port: '7023'
          env_directory: '.env.tflmi.production'
        ambnum-production:
          directory: 'ima-ambnum-production'
          port: '7025'
          env_directory: '.env.ambnum.production'
        spis-production:
          directory: 'ima-spis-production'
          port: '7027'
          env_directory: '.env.spis.production'
